import AVFoundation
import UIKit

/// Short sound effects bundled as WAV files (generated by tools/make_sfx.py).
enum SFX: String, CaseIterable {
    case tap, coin, cash, pop, upgrade, levelup, error, chest, reward, whoosh, tick, wrong, correct

    func play(volume: Float = 1) { AudioEngine.shared.play(self, volume: volume) }
}

/// Plays sound effects with a small pool of players per sound so rapid taps overlap.
/// Uses the ambient category so the game never interrupts the player's music.
final class AudioEngine {
    static let shared = AudioEngine()

    var enabled = true
    private var pools: [SFX: [AVAudioPlayer]] = [:]
    private var lastPlayed: [SFX: TimeInterval] = [:]

    private init() {
        try? AVAudioSession.sharedInstance().setCategory(.ambient, options: [.mixWithOthers])
        for s in SFX.allCases {
            guard let url = Bundle.main.url(forResource: s.rawValue, withExtension: "wav") else { continue }
            let count = (s == .tap || s == .coin || s == .tick) ? 4 : 2
            pools[s] = (0..<count).compactMap { _ in
                let p = try? AVAudioPlayer(contentsOf: url)
                p?.prepareToPlay()
                return p
            }
        }
    }

    func play(_ s: SFX, volume: Float = 1) {
        guard enabled, let pool = pools[s], !pool.isEmpty else { return }
        // Avoid machine-gun stacking of the same sound within 35ms.
        let now = ProcessInfo.processInfo.systemUptime
        if let last = lastPlayed[s], now - last < 0.035 { return }
        lastPlayed[s] = now
        let player = pool.first(where: { !$0.isPlaying }) ?? pool[0]
        player.volume = volume
        player.currentTime = 0
        player.play()
    }
}

/// Haptic feedback with prepared generators.
enum Haptic {
    static var enabled = true

    private static let light = UIImpactFeedbackGenerator(style: .light)
    private static let medium = UIImpactFeedbackGenerator(style: .medium)
    private static let heavy = UIImpactFeedbackGenerator(style: .heavy)
    private static let rigid = UIImpactFeedbackGenerator(style: .rigid)
    private static let selection = UISelectionFeedbackGenerator()
    private static let notify = UINotificationFeedbackGenerator()

    static func tap() { if enabled { light.impactOccurred() } }
    static func press() { if enabled { medium.impactOccurred() } }
    static func thud() { if enabled { heavy.impactOccurred() } }
    static func click() { if enabled { rigid.impactOccurred(intensity: 0.7) } }
    static func select() { if enabled { selection.selectionChanged() } }
    static func success() { if enabled { notify.notificationOccurred(.success) } }
    static func warning() { if enabled { notify.notificationOccurred(.warning) } }
    static func error() { if enabled { notify.notificationOccurred(.error) } }
}
